services:
  jekyll:
    build:
      context: .
    ports:
      - "4000:4000"
    volumes:
      - ./app:/usr/src/app   # Map the app directory on the host to /usr/src/app in the container
    working_dir: /usr/src/app # Set the working directory inside the container
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --force_polling
